# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "Clemens Kaserer"

# A description of your site for social meta tag, search engines, and feed.xml
description: ""

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://ckaserer.github.io"

# Author information - author info at the bottom of the post
author_name: "Clemens Kaserer"

# Social links in the site footer
linkedin_username: "ckaserer"
github_username: "ckaserer"
dockerhub_username: "ckaserer"
ansible_username: "ckaserer"

# ##################################################
# Settings for builing master branch with travis-ci
# with jekyll-travis

# Settings for deploy rake task
# Username and repo of Github repo, e.g.
# https://github.com/USERNAME/REPO.git
# username defaults to ENV['GIT_NAME'] used by Travis
# repo defaults to USERNAME.github.io
# Branch defaults to "source" for USERNAME.github.io
# or "master" otherwise
username: ckaserer
repo: ckaserer.github.io
branch: source
destination: ../master/

exclude:
  - .travis.yml
  - index-*.html
  - Gemfile
  - Gemfile.lock
  - Rakefile
  #- README.md